import type { Metadata } from "next";
import "./globals.css";
import { Context } from "./context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Context>
        <body>{children}</body>
      </Context>
    </html>
  );
}
